### ISSUE TITLE
Toon climate and smartmeter not working since 0.89

### ISSUE THREAD

**Issue by pdwonline** [cyberjunky/home-assistant-custom-components#23]
Since HA 0.89, Toon came with the following error:

```
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/entity_platform.py", line 124, in _async_setup_platform
    task = async_create_setup_task()
  File "/usr/src/app/homeassistant/helpers/entity_platform.py", line 89, in async_create_setup_task
    None, platform.setup_platform, hass, platform_config,
AttributeError: module 'homeassistant.components.toon.climate' has no attribute 'setup_platform'

```
I have already placed the python script in a folder named 'toon and renamed the .py files to climate.py and sensor.py for release 0.88

**Comment by cyberjunky** [comment]
Update your components from repo. They should be fixed.
If you use the google assistant version, I will fix this later today.

**Comment by pdwonline** [comment]
Thanks! I updated them and the smartmeter is working again! However, the Toon climate component is not (same error)

**Comment by cyberjunky** [comment]
Do you use the google assistant one? (from issue #13) or the default one from toon repo directory? The last one should work.

**Comment by cyberjunky** [comment]
I have put the google assistant one in toon_google directory.
Still have to fix switching modes and manual.
Will try to look into this today.

**Comment by pdwonline** [comment]
I used the default climate component from the toon repo directory and placed it in the folder 'custom_components/toon' but it doesn work. still getting this error:

```
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/entity_platform.py", line 124, in _async_setup_platform
    task = async_create_setup_task()
  File "/usr/src/app/homeassistant/helpers/entity_platform.py", line 89, in async_create_setup_task
    None, platform.setup_platform, hass, platform_config,
AttributeError: module 'homeassistant.components.toon.climate' has no attribute 'setup_platform'
```
Up to 0.88 it worked fine

**Comment by pdwonline** [comment]
Probably it has something to do with this change: https://github.com/home-assistant/home-assistant/pull/21070
Does it mean I have to include a climate component also in the same folder?  (and where do I get that component?)

**Comment by cyberjunky** [comment]
Did you look at the repo, read the README.md file and looked into the toon and/or toon_google directory?

You can find the climate.py file inside it (which is simply the old toon.py file) and a empty `__init__.py` file, both need to be copied (like the README described) to your toon dir, and you must remove the old toon.py file.

I use them with 0.89.1 without issues.

**Comment by pdwonline** [comment]
You'te right, i missed the __init__.py file!  Thank You!
